### ISSUE TITLE
Flight Flag Definition not honoring MemberOfSecurityGroup filter entry 

### ISSUE THREAD

**Issue by brennanmann** [microsoft/FeatureFlightingManagement#39]
Hi, Feature Flight Management Team,

In one of our feature flights, the security group operator is not honoring all the MemberOfSecurityGroup filter entries. This seems to be happening intermittently. Details sent via private message.

Please advise.

**Comment by patrickCode** [comment]
RCA
A day-0 bug in the caching framework caused the issue.
